### ISSUE TITLE
"Error: No transactions for that wallet found"

### ISSUE THREAD

**Issue by f00lfighter** [pwillworth/dfkreport#27]
I am receiving the following error while pasting in my wallet address: 
"Error: No transactions for that wallet found"

I am using the correct wallet I used while trying out DFK. I've tried checking against DFK tracker, which shows my transactions for the same wallet address.

Have you seen this issue or do you have a suggestion?

**Comment by pwillworth** [comment]
Only other possibility would be that is is failing to lookup the tx count on one of the blockchains for some reason.  If you want to share an image of the error message box with the long number at the end I can look into it.

**Comment by f00lfighter** [comment]
Thanks for checking. I realized I had not tried to reduce the time span, since I only used DFK while it was on the Harmony blockchain. This was able to generate the report!
