### ISSUE TITLE
Lila's Ledger DefiKingdoms 2023 report issues

### ISSUE THREAD

**Issue by jeffreytal** [pwillworth/dfkreport#33]
Hello,

For DefiKingdoms: Lila’s Ledger, I would like to download the Legacy Tax Report for my 2023 transactions, as I used the same report for 2022 taxes.
However, when I run the report, it is only pulling transactions from 2022 even though I have selected 1/1/23-12/31/23 as the date range.
Do you know what the root cause of the issue is? Is there any steps or advice you could give for my end?

Thank you for your help

**Comment by pwillworth** [comment]
When you put in the date range and other selections, a list should pop up with your wallets and chains selected showing how much data has been updated for them.  You might need to click the "Update" button and wait for the data to be loaded before running the report.

**Comment by jeffreytal** [comment]
Thanks for that. I did Update the transcations through today's date and I see all the transactions have been successfully updated. However, still when I run the report for all transactions during 2023, under "CSV Format" I select "Manual" and "Prepare CSV" it says "Preparing CSV" constantly for many hours and never seems to export the report. My guess is it could take a day to generate the report? Does this seem normal? I have about 300 or so transactions in total. When I generate a report for 2024 it is very quick since I have no transactions during the year, and as I expect the report is blank.

**Comment by pwillworth** [comment]
I think I see a bug that might be the cause, and will look into and test it when I get a chance.  In the meantime, if it is what I think it is, you should be able to work around it by just picking a CSV Format other than Default.

**Comment by jeffreytal** [comment]
I see. How do I export the CSV other than Default format?
